# docker-compose.yml

version: "3"

services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./:/visualeasy-front
      - /visualeasy-front/node_modules
      - /visualeasy-front/.next
    ports:
      - 3000:3000